name: maktabeh_app
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  shared_preferences: any
  dio: ^3.0.9
  rxdart: ^0.24.1
  fluttertoast: ^3.1.0
  flutter_bloc: ^6.1.1
  built_value: ^7.1.0
  floor: ^0.14.0
  analyzer: ^0.39.14
  image_picker: ^0.6.7+4
  dio_cookie_manager: ^1.0.0
  flutter_svg: ^0.19.0
  get_it: ^3.0.1
  cupertino_icons: any
  lottie: ^0.7.0+1
  cached_network_image:
  flutter_rating_bar: ^3.2.0+1
  smooth_star_rating: ^1.1.1
  dots_indicator: ^1.2.0
  esys_flutter_share: any
  url_launcher: 5.7.10
  social_share: ^1.0.8
  share: any
  firebase_messaging: ^7.0.3
  # ^1.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  floor_generator: ^0.13.0
  build_runner: ^1.10.0
  built_value_generator: ^7.1.0
  flutter_launcher_icons: "^0.7.0"
#   integration_test:
#     sdk: flutter

# dependency_overrides:
#   analyzer: ^0.41.1
#   _fe_analyzer_shared: ^14.0.0


flutter:

  uses-material-design: true
  assets:
    - assets/image/
    - assets/fonts/
    - assets/svg/
    - assets/icons/
    - assets/gif/
    - assets/lang/en.json
    - assets/lang/ar.json



  fonts:
    - family: regular
      fonts:
        - asset: assets/fonts/Noor-Regular.ttf


    - family: light
      fonts:
        - asset: assets/fonts/Noor-Light.ttf

    - family: bold
      fonts:
        - asset: assets/fonts/Noor-Bold.ttf
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf





